<?php

  function xmldb_local_eexcess_upgrade($oldversion) {
    global $DB;
    $dbman = $DB->get_manager();

    /// Add a new column newcol to the mdl_myqtype_options
    if ($oldversion < 2016022902) {
      // Code to add the column, generated by the 'View PHP Code' option of the XMLDB editor.
      // Define table local_eexcess_references to be created.
      $table = new xmldb_table('local_eexcess_references');

      // Adding fields to table local_eexcess_references.
      $table->add_field('id', XMLDB_TYPE_INTEGER, '10', null, XMLDB_NOTNULL, XMLDB_SEQUENCE, null);
      $table->add_field('userid', XMLDB_TYPE_INTEGER, '10', null, XMLDB_NOTNULL, null, null);
      $table->add_field('timestamp', XMLDB_TYPE_INTEGER, '10', null, null, null, null);
      $table->add_field('reference_type', XMLDB_TYPE_TEXT, null, null, null, null, null);
      $table->add_field('reference_to_id', XMLDB_TYPE_TEXT, null, null, null, null, null);
      $table->add_field('reference_to_uri', XMLDB_TYPE_TEXT, null, null, null, null, null);
      $table->add_field('reference_to_title', XMLDB_TYPE_TEXT, null, null, null, null, null);
      $table->add_field('reference_to_preview', XMLDB_TYPE_TEXT, null, null, null, null, null);
      $table->add_field('reference_to_facets', XMLDB_TYPE_TEXT, null, null, null, null, null);
      $table->add_field('reference_from_uri', XMLDB_TYPE_TEXT, null, null, null, null, null);
      $table->add_field('reference_from_title', XMLDB_TYPE_TEXT, null, null, null, null, null);

      // Adding keys to table local_eexcess_references.
      $table->add_key('primary', XMLDB_KEY_PRIMARY, array('id'));

      // Conditionally launch create table for local_eexcess_references.
      if (!$dbman->table_exists($table)) {
        $dbman->create_table($table);
      }

      // Eexcess savepoint reached.
      upgrade_plugin_savepoint(true, 2016022902, 'local', 'eexcess');
    }

    return TRUE;
  }
