<?php

  function xmldb_block_eexcess_upgrade($oldversion) {
    global $DB;
    $dbman = $DB->get_manager();

    /// Add a new column newcol to the mdl_myqtype_options
    if ($oldversion < 2016042802) {
      // Code to add the column, generated by the 'View PHP Code' option of the XMLDB editor.
      // Define table block_eexcess_references to be created.
      $table_references = new xmldb_table('block_eexcess_references');

      // Adding fields to table block_eexcess_references.
      $table_references->add_field('id', XMLDB_TYPE_INTEGER, '10', NULL, XMLDB_NOTNULL, XMLDB_SEQUENCE, NULL);
      $table_references->add_field('userid', XMLDB_TYPE_INTEGER, '10', NULL, XMLDB_NOTNULL, NULL, NULL);
      $table_references->add_field('timestamp', XMLDB_TYPE_INTEGER, '10', NULL, NULL, NULL, NULL);
      $table_references->add_field('reference_type', XMLDB_TYPE_TEXT, NULL, NULL, NULL, NULL, NULL);
      $table_references->add_field('reference_to_id', XMLDB_TYPE_TEXT, NULL, NULL, NULL, NULL, NULL);
      $table_references->add_field('reference_to_uri', XMLDB_TYPE_TEXT, NULL, NULL, NULL, NULL, NULL);
      $table_references->add_field('reference_to_title', XMLDB_TYPE_TEXT, NULL, NULL, NULL, NULL, NULL);
      $table_references->add_field('reference_to_preview', XMLDB_TYPE_TEXT, NULL, NULL, NULL, NULL, NULL);
      $table_references->add_field('reference_to_facets', XMLDB_TYPE_TEXT, NULL, NULL, NULL, NULL, NULL);
      $table_references->add_field('reference_from_uri', XMLDB_TYPE_TEXT, NULL, NULL, NULL, NULL, NULL);
      $table_references->add_field('reference_from_title', XMLDB_TYPE_TEXT, NULL, NULL, NULL, NULL, NULL);

      // Adding keys to table block_eexcess_references.
      $table_references->add_key('primary', XMLDB_KEY_PRIMARY, array('id'));

      // Conditionally launch create table for block_eexcess_references.
      if (!$dbman->table_exists($table_references)) {
        $dbman->create_table($table_references);
      }

      // Code to add the column, generated by the 'View PHP Code' option of the XMLDB editor.
      // Define table block_eexcess_references to be created.
      $table_history = new xmldb_table('block_eexcess_history');

      // Adding fields to table block_eexcess_references.
      $table_history->add_field('id', XMLDB_TYPE_INTEGER, '10', NULL, XMLDB_NOTNULL, XMLDB_SEQUENCE, NULL);
      $table_history->add_field('userid', XMLDB_TYPE_INTEGER, '10', NULL, XMLDB_NOTNULL, NULL, NULL);
      $table_history->add_field('timestamp', XMLDB_TYPE_INTEGER, '10', NULL, NULL, NULL, NULL);
      $table_history->add_field('json', XMLDB_TYPE_TEXT, NULL, NULL, NULL, NULL, NULL);

      // Adding keys to table block_eexcess_references.
      $table_history->add_key('primary', XMLDB_KEY_PRIMARY, array('id'));

      // Conditionally launch create table for block_eexcess_references.
      if (!$dbman->table_exists($table_history)) {
        $dbman->create_table($table_history);
      }

      // Eexcess savepoint reached.
      upgrade_plugin_savepoint(TRUE, 2016042802, 'block', 'eexcess');
    }

    return TRUE;
  }
